apiVersion: apps/v1
kind: Deployment
metadata:
  name: bk_deploy
  labels:
    app: bk_deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app:  bk_deploy
  template:
    metadata:
      labels:
        app:  bk_deploy
    spec:
      containers:
      - name: bk-container
        image: shanth19611356248/bk_app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bk_service
  labels:
    app:  bk_deploy
spec:
  selector:
    app:  bk_deploy
  type: NodePort
  ports:
  - nodePort: 31203
    port: 8082
    targetPort: 8082
