apiVersion: apps/v1
kind: Deployment
metadata:
  name: bkdeploy1
  labels:
    app: bkdeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app:  bkdeploy
  template:
    metadata:
      labels:
        app:  bkdeploy
    spec:
      containers:
      - name: bkcontainer
        image: shanth19611356248/bk_app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bankservice
  labels:
    app:  bkdeploy
spec:
  selector:
    app:  bkdeploy
  type: NodePort
  ports:
  - nodePort: 31300
    port: 8082
    targetPort: 8082
